server:
  port: 8000

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tianhuan168/boot-cloud-config/
          search-paths: config-repo
          username: 565267436@qq.com
          password: sssssupdate00121+52749
eureka:
  client:
    service-url:
      defaultZone: http://39.105.0.233:8761/:8001/eureka/
